# Generated by Django 2.2 on 2019-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lesson_plans", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="book",
            field=models.CharField(default="", max_length=200, verbose_name="book"),
        )
    ]
