# Generated by Django 2.2 on 2019-04-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lesson_plans", "0005_auto_20190414_1639")]

    operations = [migrations.RemoveField(model_name="lesson", name="lesson_number")]
