# Generated by Django 2.2 on 2019-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lesson_plans", "0008_auto_20190414_1651")]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_number",
            field=models.IntegerField(default=0, verbose_name="lesson number"),
        )
    ]
